source 'http://rubygems.org'

ruby '2.0.0'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'json'

#database
gem "mysql2"
#O/R mapper
gem "activerecord"

#twitter omniauth
#gem 'omniauth-twitter'
#gem 'twitter'
#gem 'dotenv'


